name: Trigger Embedding Notebook

on:
  push:
    paths:
      - "Articles.csv"

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Colab webhook
        run: |
          curl -X POST https://0526761a6af6.ngrok-free.app/refresh
