name: Trigger Embedding Notebook

on:
  push:
    branches: [ main ]
    paths:
      - "Articles.csv"           # match the exact filename/case
  workflow_dispatch: {}          # allow manual run

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Colab webhook
        run: |
          echo "Notifying Colab webhook..."
          curl -sS -X POST https://0526761a6af6.ngrok-free.app/refresh
