name: Trigger Embedding Notebook

on:
  push:
    branches: [ main ]
    paths:
      - "Articles.csv"
  workflow_dispatch: {}

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Health check (up to 5x)
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}   # e.g. https://abc123.trycloudflare.com
        run: |
          set -e
          for i in {1..5}; do
            echo "Health check ($i/5)…"
            if curl -fsS "$WEBHOOK_URL/healthz" > /dev/null; then
              echo "OK"; exit 0
            fi
            sleep 5
          done
          echo "Health endpoint not reachable"; exit 1

      - name: Trigger refresh
        env:
          WEBHOOK_URL:   ${{ secrets.WEBHOOK_URL }}
          WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}
        run: |
          echo "POST $WEBHOOK_URL/refresh"
          curl -sS -D headers.txt -o body.txt -X POST \
               -H "X-Webhook-Token: $WEBHOOK_TOKEN" \
               "$WEBHOOK_URL/refresh"
          echo "---- headers ----"; cat headers.txt
          echo "---- body ----"; cat body.txt
          CODE=$(grep HTTP headers.txt | tail -1 | awk '{print $2}')
          [ "$CODE" -ge 200 ] && [ "$CODE" -lt 300 ] || { echo "Non-2xx: $CODE"; exit 1; }
